# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /PROJET_ML_FAUDE

# Copy the current directory contents into the container at /app
COPY . /PROJET_ML_FAUDE

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirementscollect.txt

# Make port 5000 available to the world outside this container
EXPOSE 5001

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "script_collect_data_fraude.py"]
