env:
  DOCKER_USER: 'hawadioni'  # ${{secrets.hawadioni}}
  DOCKER_PASSWORD: 'Haw@0102d' # ${{ secrets.Haw@0102d }}
  DOCKER_REPO_NAME:  'model_detection_fraude' #${{secrets.model_detection_fraude}}
 # MON_TEST: ${{secrets.MON_TEST_PWD}}


on:
  push:
    branches:
      - dockerMl
  pull_request:
    branches:
      - dockerMl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build . -f Dockerfile -t mldetectionfraude

      - name: List of Docker images
        run: docker image ls

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 mldetectionfraude

      - name: List of Docker -a AFTER
        run: docker ps -a

      - name: List of Docker -q AFTER
        run: docker ps --filter "ancestor=mldetectionfraude" -q

      - name: Docker Login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image with Tag
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.date.outputs.date }}


      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.date.outputs.date }}

      - name: Stop Docker Container
        run: docker stop $(docker ps --filter "ancestor=mldetectionfraude" -q)






      - name: Build Docker Image2
        run: docker build . -f Dockerfile_collect -t collectdetectionfraude

      - name: List of Docker images
        run: docker image ls

      - name: Run Docker Container2
        run: docker run -d -p 5001:5000 collectdetectionfraude

      - name: List of Docker -a AFTER
        run: docker ps -a

      - name: List of Docker -q AFTER
        run: docker ps --filter "ancestor=collectdetectionfraude" -q


      - name: Docker Login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Get Current Date
        id: Dates
        run: echo "::set-output name=Dates::$(Dates +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image with Tag
        run: docker build . --file Dockerfile_collect --tag $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.Dates.outputs.Dates }}


      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.Dates.outputs.Dates }}

      - name: Stop Docker Container
        run: docker stop $(docker ps --filter "ancestor=collectdetectionfraude" -q)