on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Build Docker Image
          run: docker build . -f Dockerfile -t mldetectionfraude

        # - name: Build Docker Image2
        #   run: docker build . -f Dockerfilre_collect -t collectdetectionfraude

        - name: List of Docker images
          run: docker image ls
  
        - name: Run Docker Container
          run: docker run -d -p 5000:5000 mldetectionfraude
        
        # - name: Run Docker Container2
        #   run: docker run -d -p 5001:5000 collectdetectionfraude
  
  
        - name: List of Docker -a AFTER
          run: docker ps -a  
  
        - name: List of Docker -q AFTER
          run: docker ps --filter "ancestor=mldetectionfraude" -q
  
        # - name: List of Docker -q AFTER
        #   run: docker ps --filter "ancestor=collectdetectionfraude" -q
  
        # - name: Test
        #   run: docker exec $(docker ps --filter "ancestor=emldetectionfraude" -q) python -m unittest discover tests

        