
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build . -t flaskappgitactions

      - name: List Docker Images
        run: docker image ls

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 flaskappgitactions

      - name: List Docker Containers AFTER
        run: docker ps -a

      - name: List Docker Containers ID AFTER
        run: docker ps --filter "ancestor=flaskappgitactions" -q

