env:
  DOCKER_USER: 'hawadioni'  # ${{secrets.hawadioni}}
  DOCKER_PASSWORD: 'Haw@0102d' # ${{ secrets.Haw@0102d }}
  DOCKER_REPO_NAME: ${{secrets.model_detection_fraude}}
  MON_TEST: ${{secrets.MON_TEST_PWD}}

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build . -t flaskappgitactions

      - name: List Docker Images
        run: docker image ls

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 flaskappgitactions

      - name: List Docker Containers AFTER
        run: docker ps -a

      - name: List Docker Containers ID AFTER
        run: docker ps --filter "ancestor=flaskappgitactions" -q

      #- name: Test Docker Container
       # run: docker exec $(docker ps --filter "ancestor=flaskappgitactions" -q) python -m unittest discover ../../tests

      - name: Docker Login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image with Tag
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPO_NAME:2024-03-06-38-29

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.date.outputs.date }}

      - name: Stop Docker Container
        run: docker stop $(docker ps --filter "ancestor=flaskappgitactions" -q)
